// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOdZV_lz8_9KEdSKqCbOX-zJ5dGNilSpk',
    appId: '1:929440554591:web:7c1f95cd5a0d24e62445ea',
    messagingSenderId: '929440554591',
    projectId: 'justice-b9f4a',
    authDomain: 'justice-b9f4a.firebaseapp.com',
    storageBucket: 'justice-b9f4a.firebasestorage.app',
    measurementId: 'G-NZ1CDJNW38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq3di0984sPRAFqbQa-sSlw1tRTcjdd_Q',
    appId: '1:929440554591:android:c72118c0e817b4c72445ea',
    messagingSenderId: '929440554591',
    projectId: 'justice-b9f4a',
    storageBucket: 'justice-b9f4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7QRFHyvEdAh-xEGA_q7xFv-DUsGCC86Y',
    appId: '1:929440554591:ios:fd4c5306fac38ede2445ea',
    messagingSenderId: '929440554591',
    projectId: 'justice-b9f4a',
    storageBucket: 'justice-b9f4a.firebasestorage.app',
    iosBundleId: 'com.example.justiceComplaints',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7QRFHyvEdAh-xEGA_q7xFv-DUsGCC86Y',
    appId: '1:929440554591:ios:fd4c5306fac38ede2445ea',
    messagingSenderId: '929440554591',
    projectId: 'justice-b9f4a',
    storageBucket: 'justice-b9f4a.firebasestorage.app',
    iosBundleId: 'com.example.justiceComplaints',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOdZV_lz8_9KEdSKqCbOX-zJ5dGNilSpk',
    appId: '1:929440554591:web:bb0dc04dbdf6d9512445ea',
    messagingSenderId: '929440554591',
    projectId: 'justice-b9f4a',
    authDomain: 'justice-b9f4a.firebaseapp.com',
    storageBucket: 'justice-b9f4a.firebasestorage.app',
    measurementId: 'G-EN0CVMXY4N',
  );
}
